### ISSUE TITLE
sign_up()

### ISSUE THREAD

**Issue by AishaSR** [AishaSR/SYSC5709W-Project#4]
Develop the function to collect and validate USER data on sign up and add it to the database (FILE system).

**Comment by Ramya-MB** [comment]
Waiting for the **_add_record_** function to be implemented. So it can be called from inside the _**sign_up**_ function to add the new user's details into the file(database).

**Comment by Mitali92** [comment]
add_record has been completed and you can just check sign_up() function by adding your sign up data to the add_record function.
